server:
  port: 8087

spring:
  application:
    name: leyou-auth-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

#feign:
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false

leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: F:\ideaproject\leyou\leyou-auth\rsa\rsa.pub # 公钥地址
    priKeyPath: F:\ideaproject\leyou\leyou-auth\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN