server:
  port: 8091
spring:
  application:
    name: leyou-item-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.48.130
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期
logging:
  level:
    com.leyou.item: debug
