server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.48.130
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4GCTTBkvmeeLxYyBth53 # 你自己的accessKeyId
    accessKeySecret: zXw9hlrtV2LqWiL0doBHaU5eOlSQVn # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: sms_202565699 # 模板名称