server:
  port: 8088

spring:
  application:
    name: leyou-cart-service
  redis:
    host: 192.168.48.130

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

leyou:
  jwt:
    pubKeyPath: F:\ideaproject\leyou\leyou-auth\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN